spring.application.name=miniproject
spring.datasource.url=jdbc:mysql://localhost:3307/miniproject
spring.datasource.username=root
spring.datasource.password=1234

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

logging.level.org.thymeleaf=DEBUG

server.port=8081

# ===============================
# MULTIPART FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

# Tomcat post size limit (ต้องตั้งให้ >= max-request-size)
server.tomcat.max-http-form-post-size=100MB
server.tomcat.max-part-count=50

#ตั้งค่า Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tourism.notify@gmail.com
spring.mail.password=pvzi vizj lfau ncoe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true